/**
    @file properties.cpp
 
    @author Manfred Morgner
    @date 15.04.2018

    Demonstrates how Properties are added to the mix. Here the properties are
    autogenerated to simplify the program. Even if they are generated 
    automatically, they are only generated ones each. Automatic helper
    functions prevent the odb from becoming filled up with duplicates
 */

#include <iostream>

#include "generic.h"
#include "odb.h"
#include "atom.h"
#include "node.h"

auto oOdb = odb::COdb();


// Demo main program
int main()
    {
    // 3 people
    oOdb.MakeNode("Udo");
    oOdb.MakeNode("Ina");
    oOdb.MakeNode("Rob");

    // 3 kind of relation
    oOdb.MakeReason("is father of");
    oOdb.MakeReason("knows");
    oOdb.MakeReason("loves");
    
    // 3 bindings
    oOdb.LinkNode2Node("Udo", "is father of", "Ina");
    oOdb.LinkNode2Node("Udo", "knows"       , "Rob");
    oOdb.LinkNode2Node("Ina", "loves"       , "Rob");


    oOdb.AppendProperty2Node("sex:male"  , true, "Udo");
                                                       
    oOdb.AppendProperty2Node("born:1999" , true, "Ina");
    oOdb.AppendProperty2Node("sex:female", true, "Ina");
                                                       
    oOdb.AppendProperty2Node("sex:male"  , true, "Rob");

    // show us
    std::cout << "---------------- all nodes" << '\n';
    for ( auto const & a:oOdb.Nodes() )
        {
        std::cout << *a << '\n';
        }
    }

